IF OBJECT_ID ('dbo.fCfdIMPRIME_COMPROBANTE_DTE') IS NOT NULL
   DROP FUNCTION dbo.fCfdIMPRIME_COMPROBANTE_DTE
GO

create function dbo.fCfdIMPRIME_COMPROBANTE_DTE()
returns TABLE 
as
--Propósito. Obtiene las facturas a imprimir
--3/10/14 jcf Creación
--10/11/16 jcf corrige user_id
--27/07/17 jcf cambia ruta de código de barras
--
return (
SELECT 1 LINEA, A.SOPNUMBE, A.SOPTYPE, isnull(dte.FchEmis, A.docdate) DOCDATE, A.SUBTOTAL, A.TAXAMNT, A.DOCAMNT, 
	A.CUSTNMBR, DUEDATE, CASE WHEN ISNULL(I.DUEDTDS, 30) = 0 THEN 'Contado' ELSE CONVERT(VARCHAR,ISNULL(I.DUEDTDS, 30)) + ' días' END PYMTRMID, 
	0 user_id, 
--	CONVERT(INT, A.CUSTNMBR) user_id, 
	dte.Folio,
	dte.RznSocRecep CUSTNAME, 
	dte.DirRecep ADDRESS1, B.ADDRESS2, B.ADDRESS3, 
	dte.CiudadRecep CITY,
	dte.CmnaRecep STATE, 
	B.COUNTRY, B.ZIP, B.PHONE1, 
	B.PHONE2, B.FAX, 
	dte.RUTRecep tax_number, 
	ISNULL(LTRIM(RTRIM((CONVERT(CHAR(400), F.TXTFIELD)))) + ' -  ' + ISNULL(H.description, ''), '')  address, 
	CO.CCode address_country_code, 
	ISNULL(RTRIM(CONVERT(CHAR(400),D.CMMTTEXT)), '') shipping_address, 
	'' shipping_address_country_code, '' license_address, 
	'' license_address_country_code,
	CONVERT(int, ISNULL(CL.INTEGRATIONID, '0')) article_id, C.ITEMNMBR, C.ITEMDESC ITEMDESC, 
	C.UNITPRCE, 
	C.XTNDPRCE, C.QUANTITY, 
	ISNULL(E.CMMTTEXT, '') info, C.ShipToName img_url, DYNAMICS.dbo.fncNUMLET(A.CURNCYID, A.DOCAMNT) CURTEXT, 
	ISNULL(D.USERDEF1, '') ORDENVTA,
	ISNULL(D.USRDAT01, 0) FECHAORDVTA, B.USERDEF1, ISNULL(G.LOCATNNM, '') TRANSFA, ISNULL(G.ADRCNTCT, '') BANCO, 
	ISNULL(G.ADDRESS1, '') CUENTA, ISNULL(G.ADDRESS2, '') CBU, ISNULL(G.ADDRESS3, '') TRANSFTIT, CO.ADRCNTCT CMPNYNAM, CO.ADDRESS1 ADDRESS1CO,
	CO.ZIPCODE ZIPCODECO, CO.CITY CITYCO, CO.ADDRESS2 TELCO, CO.STATE MAIL1CO, CO.ADDRESS3 MAIL2CO, CO.CMPNYNAM EMPRESA, CO.TAXREGTN,
	A.CURNCYID, A.TRDISAMT, 
	dte.GiroRecep COMMENT1,
	A.CSTPONBR ORDCPRA,
	ISNULL(D.USERDEF2, '') TIPOTRABAJO,
	ISNULL(D.USRDEF03, '') PEDIDOPOR,
	ISNULL(D.USRDEF04, '') CLIENTE,
	ISNULL(D.USRDEF05, '') PROMOCION,
	ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'VENTAS'), '') DIRVTAS,
	ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'DIRECCION'), '') DIRDIRE,
	ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'BANCO'), '') DIRBCO,
	ISNULL(HD.memo, '') memo,
	ISNULL((select TOP 1 CHEKBKID from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKBKID,
	A.PYMTRCVD, A.ACCTAMNT, ISNULL((select TOP 1 CHEKNMBR from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKNMBR,
	A.REFRENCE, dte.docType, dte.nombreTipoDoc, dte.TpoDocRef, dte.FolioRef,  dte.FchRef, dte.nombreTipoDocRef,
	--dbo.fCfdObtieneImagenCruda('file://C:\GETTY' + Stuff(rutaYNomArchivoNet, 1, 14, '')) codigoBarras,
	dbo.fCfdObtieneImagenCruda(dte.rutaYNomArchivoNet) codigoBarras,
	dte.nroResol, dte.fchResol,
	'SOP30200' sTabla
FROM
	SOP30200 A 
	INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
	INNER JOIN SOP30300 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
	LEFT JOIN vwCfdDocumentosAImprimir dte on dte.soptype = C.SOPTYPE AND dte.sopnumbe = C.SOPNUMBE 
	LEFT OUTER JOIN INT_SOPHDR HD ON A.SOPTYPE = HD.SOPTYPE AND A.SOPNUMBE = HD.SOPNUMBE
	LEFT OUTER JOIN INT_SOPLINE CL ON C.SOPTYPE = CL.SOPTYPE AND C.SOPNUMBE = CL.SOPNUMBE AND C.LNITMSEQ = CL.LNITMSEQ
	LEFT OUTER JOIN DYNAMICS..SY01500 CO ON CO.INTERID = DB_NAME()
	LEFT OUTER JOIN SOP10106 D ON A.SOPTYPE = D.SOPTYPE AND A.SOPNUMBE = D.SOPNUMBE 
	LEFT OUTER JOIN SOP10202 E ON E.SOPTYPE = A.SOPTYPE AND E.SOPNUMBE = A.SOPNUMBE AND E.LNITMSEQ = C.LNITMSEQ
	LEFT OUTER JOIN SY03900 F ON A.NOTEINDX = F.NOTEINDX
	LEFT OUTER JOIN SY00600 G ON G.LOCATNID = 'BANCO'
	LEFT OUTER JOIN INTDB2..ERP_Country_Description H ON B.COUNTRY = H.country_code AND language_code = 'es'
	LEFT OUTER JOIN SY03300 I ON A.PYMTRMID = I.PYMTRMID
) 
go

--UNION ALL

--SELECT 1 LINEA, A.SOPNUMBE, A.SOPTYPE, A.DOCDATE, A.SUBTOTAL, A.TAXAMNT, A.DOCAMNT, 
--	A.CUSTNMBR, DUEDATE, CASE WHEN ISNULL(I.DUEDTDS, 30) = 0 THEN 'Contado' ELSE CONVERT(VARCHAR,ISNULL(I.DUEDTDS, 30)) + ' días' END PYMTRMID, 
--	CONVERT(INT, A.CUSTNMBR) user_id, 
--	'' Folio,
--	A.CUSTNAME, B.ADDRESS1, B.ADDRESS2, B.ADDRESS3, B.CITY, B.STATE, 
--	B.COUNTRY, B.ZIP, B.PHONE1, 
--	B.PHONE2, B.FAX, B.TXRGNNUM tax_number, 
--	ISNULL(LTRIM(RTRIM((CONVERT(CHAR(400), F.TXTFIELD)))) + ' -  ' + ISNULL(H.description, ''), '')  address, 
--	--F.TXTFIELD address,
--	CO.CCode address_country_code, 
--	ISNULL(RTRIM(CONVERT(CHAR(400),D.CMMTTEXT)), '') shipping_address, 
--	'' shipping_address_country_code, '' license_address, 
--	'' license_address_country_code,
--	CONVERT(int, C.INTEGRATIONID) article_id, C.ITEMNMBR, C.ITEMDESC ITEMDESC, 
--	C.UNITPRCE, 
--	C.XTNDPRCE, C.QUANTITY, 
--	ISNULL(E.CMMTTEXT, '') info, C.ShipToName img_url, DYNAMICS.dbo.fncNUMLET(A.CURNCYID, A.DOCAMNT) CURTEXT, 
--	ISNULL(D.USERDEF1, '') ORDENVTA,
--	ISNULL(D.USRDAT01, 0) FECHAORDVTA, B.USERDEF1, ISNULL(G.LOCATNNM, '') TRANSFA, ISNULL(G.ADRCNTCT, '') BANCO, 
--	ISNULL(G.ADDRESS1, '') CUENTA, ISNULL(G.ADDRESS2, '') CBU, ISNULL(G.ADDRESS3, '') TRANSFTIT, CO.ADRCNTCT CMPNYNAM, CO.ADDRESS1 ADDRESS1CO,
--	CO.ZIPCODE ZIPCODECO, CO.CITY CITYCO, CO.ADDRESS2 TELCO, CO.STATE MAIL1CO, CO.ADDRESS3 MAIL2CO, CO.CMPNYNAM EMPRESA, CO.TAXREGTN,
--	A.CURNCYID, A.TRDISAMT, B.COMMENT1,
--	A.CSTPONBR ORDCPRA,
--	ISNULL(D.USERDEF2, '') TIPOTRABAJO,
--	ISNULL(D.USRDEF03, '') PEDIDOPOR,
--	ISNULL(D.USRDEF04, '') CLIENTE,
--	ISNULL(D.USRDEF05, '') PROMOCION,
--	ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'VENTAS'), '') DIRVTAS,
--	ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'DIRECCION'), '') DIRDIRE,
--	ISNULL((SELECT TXTFIELD FROM SY03900 A1, SY00600 B1 WHERE A1.NOTEINDX = B1.NOTEINDX AND B1.LOCATNID = 'BANCO'), '') DIRBCO,
--	ISNULL(HD.memo, '') memo,
--	ISNULL((select TOP 1 CHEKBKID from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKBKID,
--	A.PYMTRCVD, A.ACCTAMNT, ISNULL((select TOP 1 CHEKNMBR from SOP10103 WHERE SOPTYPE = A.SOPTYPE AND SOPNUMBE = A.SOPNUMBE), '') CHEKNMBR,
--	A.REFRENCE, '' docType, '' nombreTipoDoc, '' TpoDocRef, '' FolioRef,  '1/1/1900' FchRef, '' nombreTipoDocRef,
--	null codigoBarras, '' nroResol, '1/1/1900' fchResol,
--	'SOP10100' sTabla
--FROM
--	SOP10100 A INNER JOIN RM00101 B ON A.CUSTNMBR = B.CUSTNMBR
--	INNER JOIN SOP10200 C ON A.SOPTYPE = C.SOPTYPE AND A.SOPNUMBE = C.SOPNUMBE
--	LEFT OUTER JOIN INT_SOPHDR HD ON A.SOPTYPE = HD.SOPTYPE AND A.SOPNUMBE = HD.SOPNUMBE
--	LEFT OUTER JOIN DYNAMICS..SY01500 CO ON CO.INTERID = DB_NAME()
--	LEFT OUTER JOIN SOP10106 D ON A.SOPTYPE = D.SOPTYPE AND A.SOPNUMBE = D.SOPNUMBE 
--	LEFT OUTER JOIN SOP10202 E ON E.SOPTYPE = A.SOPTYPE AND E.SOPNUMBE = A.SOPNUMBE AND E.LNITMSEQ = C.LNITMSEQ
--	LEFT OUTER JOIN SY03900 F ON A.NOTEINDX = F.NOTEINDX
--	LEFT OUTER JOIN SY00600 G ON G.LOCATNID = 'BANCO'
--	LEFT OUTER JOIN INTDB2..ERP_Country_Description H ON B.COUNTRY = H.country_code AND language_code = 'es'
--	LEFT OUTER JOIN SY03300 I ON A.PYMTRMID = I.PYMTRMID


IF (@@Error = 0) PRINT 'Creación exitosa de: fCfdIMPRIME_COMPROBANTE_DTE()'
ELSE PRINT 'Error en la creación de: fCfdIMPRIME_COMPROBANTE_DTE()'
GO

---------------------------------------------------------------------------------------------------------
--select *
--from [IMPRIME_COMPROBANTE_DTE]
--where sopnumbe = 'FV 00008201'
