//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sii.cl/SiiDte", IsNullable=false)]
public partial class RespuestaDTE {
    
    private RespuestaDTEResultado resultadoField;
    
    private SignatureType signatureField;
    
    private decimal versionField;
    
    public RespuestaDTE() {
        this.versionField = ((decimal)(1.0m));
    }
    
    /// <remarks/>
    public RespuestaDTEResultado Resultado {
        get {
            return this.resultadoField;
        }
        set {
            this.resultadoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public partial class RespuestaDTEResultado {
    
    private RespuestaDTEResultadoCaratula caratulaField;
    
    private object[] itemsField;
    
    private string idField;
    
    /// <remarks/>
    public RespuestaDTEResultadoCaratula Caratula {
        get {
            return this.caratulaField;
        }
        set {
            this.caratulaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RecepcionEnvio", typeof(RespuestaDTEResultadoRecepcionEnvio))]
    [System.Xml.Serialization.XmlElementAttribute("ResultadoDTE", typeof(RespuestaDTEResultadoResultadoDTE))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public partial class RespuestaDTEResultadoCaratula {
    
    private string rutRespondeField;
    
    private string rutRecibeField;
    
    private string idRespuestaField;
    
    private string nroDetallesField;
    
    private string nmbContactoField;
    
    private string fonoContactoField;
    
    private string mailContactoField;
    
    private System.DateTime tmstFirmaRespField;
    
    private decimal versionField;
    
    public RespuestaDTEResultadoCaratula() {
        this.versionField = ((decimal)(1.0m));
    }
    
    /// <remarks/>
    public string RutResponde {
        get {
            return this.rutRespondeField;
        }
        set {
            this.rutRespondeField = value;
        }
    }
    
    /// <remarks/>
    public string RutRecibe {
        get {
            return this.rutRecibeField;
        }
        set {
            this.rutRecibeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string IdRespuesta {
        get {
            return this.idRespuestaField;
        }
        set {
            this.idRespuestaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NroDetalles {
        get {
            return this.nroDetallesField;
        }
        set {
            this.nroDetallesField = value;
        }
    }
    
    /// <remarks/>
    public string NmbContacto {
        get {
            return this.nmbContactoField;
        }
        set {
            this.nmbContactoField = value;
        }
    }
    
    /// <remarks/>
    public string FonoContacto {
        get {
            return this.fonoContactoField;
        }
        set {
            this.fonoContactoField = value;
        }
    }
    
    /// <remarks/>
    public string MailContacto {
        get {
            return this.mailContactoField;
        }
        set {
            this.mailContactoField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TmstFirmaResp {
        get {
            return this.tmstFirmaRespField;
        }
        set {
            this.tmstFirmaRespField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
//[System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
//public partial class SignatureType {
    
//    private SignatureTypeSignedInfo signedInfoField;
    
//    private byte[] signatureValueField;
    
//    private SignatureTypeKeyInfo keyInfoField;
    
//    /// <remarks/>
//    public SignatureTypeSignedInfo SignedInfo {
//        get {
//            return this.signedInfoField;
//        }
//        set {
//            this.signedInfoField = value;
//        }
//    }

//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
//    public byte[] SignatureValue
//    {
//        get
//        {
//            return this.signatureValueField;
//        }
//        set
//        {
//            this.signatureValueField = value;
//        }
//    }

//    /// <remarks/>
//    public SignatureTypeKeyInfo KeyInfo
//    {
//        get
//        {
//            return this.keyInfoField;
//        }
//        set
//        {
//            this.keyInfoField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeSignedInfo {
    
//    private SignatureTypeSignedInfoCanonicalizationMethod canonicalizationMethodField;
    
//    private SignatureTypeSignedInfoSignatureMethod signatureMethodField;
    
//    private SignatureTypeSignedInfoReference referenceField;
    
//    /// <remarks/>
//    public SignatureTypeSignedInfoCanonicalizationMethod CanonicalizationMethod {
//        get {
//            return this.canonicalizationMethodField;
//        }
//        set {
//            this.canonicalizationMethodField = value;
//        }
//    }
    
//    /// <remarks/>
//    public SignatureTypeSignedInfoSignatureMethod SignatureMethod {
//        get {
//            return this.signatureMethodField;
//        }
//        set {
//            this.signatureMethodField = value;
//        }
//    }
    
//    /// <remarks/>
//    public SignatureTypeSignedInfoReference Reference {
//        get {
//            return this.referenceField;
//        }
//        set {
//            this.referenceField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeSignedInfoCanonicalizationMethod {
    
//    private string algorithmField;
    
//    public SignatureTypeSignedInfoCanonicalizationMethod() {
//        this.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
//    public string Algorithm {
//        get {
//            return this.algorithmField;
//        }
//        set {
//            this.algorithmField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeSignedInfoSignatureMethod {
    
//    private SignatureTypeSignedInfoSignatureMethodAlgorithm algorithmField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public SignatureTypeSignedInfoSignatureMethodAlgorithm Algorithm {
//        get {
//            return this.algorithmField;
//        }
//        set {
//            this.algorithmField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public enum SignatureTypeSignedInfoSignatureMethodAlgorithm {
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")]
//    httpwwww3org200009xmldsigrsasha1,
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#dsa-sha1")]
//    httpwwww3org200009xmldsigdsasha1,
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeSignedInfoReference {
    
//    private SignatureTypeSignedInfoReferenceTransforms transformsField;
    
//    private SignatureTypeSignedInfoReferenceDigestMethod digestMethodField;
    
//    private byte[] digestValueField;
    
//    private string uRIField;
    
//    /// <remarks/>
//    public SignatureTypeSignedInfoReferenceTransforms Transforms {
//        get {
//            return this.transformsField;
//        }
//        set {
//            this.transformsField = value;
//        }
//    }
    
//    /// <remarks/>
//    public SignatureTypeSignedInfoReferenceDigestMethod DigestMethod {
//        get {
//            return this.digestMethodField;
//        }
//        set {
//            this.digestMethodField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] DigestValue {
//        get {
//            return this.digestValueField;
//        }
//        set {
//            this.digestValueField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
//    public string URI {
//        get {
//            return this.uRIField;
//        }
//        set {
//            this.uRIField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeSignedInfoReferenceTransforms {
    
//    private SignatureTypeSignedInfoReferenceTransformsTransform transformField;
    
//    /// <remarks/>
//    public SignatureTypeSignedInfoReferenceTransformsTransform Transform {
//        get {
//            return this.transformField;
//        }
//        set {
//            this.transformField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeSignedInfoReferenceTransformsTransform {
    
//    private string algorithmField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
//    public string Algorithm {
//        get {
//            return this.algorithmField;
//        }
//        set {
//            this.algorithmField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeSignedInfoReferenceDigestMethod {
    
//    private string algorithmField;
    
//    public SignatureTypeSignedInfoReferenceDigestMethod() {
//        this.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1";
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
//    public string Algorithm {
//        get {
//            return this.algorithmField;
//        }
//        set {
//            this.algorithmField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeKeyInfo {
    
//    private SignatureTypeKeyInfoKeyValue keyValueField;
    
//    private SignatureTypeKeyInfoX509Data x509DataField;
    
//    /// <remarks/>
//    public SignatureTypeKeyInfoKeyValue KeyValue {
//        get {
//            return this.keyValueField;
//        }
//        set {
//            this.keyValueField = value;
//        }
//    }
    
//    /// <remarks/>
//    public SignatureTypeKeyInfoX509Data X509Data {
//        get {
//            return this.x509DataField;
//        }
//        set {
//            this.x509DataField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeKeyInfoKeyValue {
    
//    private object itemField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(SignatureTypeKeyInfoKeyValueDSAKeyValue))]
//    [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(SignatureTypeKeyInfoKeyValueRSAKeyValue))]
//    public object Item {
//        get {
//            return this.itemField;
//        }
//        set {
//            this.itemField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeKeyInfoKeyValueDSAKeyValue {
    
//    private byte[] pField;
    
//    private byte[] qField;
    
//    private byte[] gField;
    
//    private byte[] yField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] P {
//        get {
//            return this.pField;
//        }
//        set {
//            this.pField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] Q {
//        get {
//            return this.qField;
//        }
//        set {
//            this.qField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] G {
//        get {
//            return this.gField;
//        }
//        set {
//            this.gField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] Y {
//        get {
//            return this.yField;
//        }
//        set {
//            this.yField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeKeyInfoKeyValueRSAKeyValue {
    
//    private byte[] modulusField;
    
//    private byte[] exponentField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] Modulus {
//        get {
//            return this.modulusField;
//        }
//        set {
//            this.modulusField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] Exponent {
//        get {
//            return this.exponentField;
//        }
//        set {
//            this.exponentField = value;
//        }
//    }
//}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
//public partial class SignatureTypeKeyInfoX509Data {
    
//    private byte[] x509CertificateField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
//    public byte[] X509Certificate {
//        get {
//            return this.x509CertificateField;
//        }
//        set {
//            this.x509CertificateField = value;
//        }
//    }
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public partial class RespuestaDTEResultadoRecepcionEnvio {
    
    private string nmbEnvioField;
    
    private System.DateTime fchRecepField;
    
    private string codEnvioField;
    
    private string envioDTEIDField;
    
    private byte[] digestField;
    
    private string rutEmisorField;
    
    private string rutReceptorField;
    
    private RespuestaDTEResultadoRecepcionEnvioEstadoRecepEnv estadoRecepEnvField;
    
    private string recepEnvGlosaField;
    
    private string nroDTEField;
    
    private RespuestaDTEResultadoRecepcionEnvioRecepcionDTE[] recepcionDTEField;
    
    /// <remarks/>
    public string NmbEnvio {
        get {
            return this.nmbEnvioField;
        }
        set {
            this.nmbEnvioField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime FchRecep {
        get {
            return this.fchRecepField;
        }
        set {
            this.fchRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string CodEnvio {
        get {
            return this.codEnvioField;
        }
        set {
            this.codEnvioField = value;
        }
    }
    
    /// <remarks/>
    public string EnvioDTEID {
        get {
            return this.envioDTEIDField;
        }
        set {
            this.envioDTEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Digest {
        get {
            return this.digestField;
        }
        set {
            this.digestField = value;
        }
    }
    
    /// <remarks/>
    public string RutEmisor {
        get {
            return this.rutEmisorField;
        }
        set {
            this.rutEmisorField = value;
        }
    }
    
    /// <remarks/>
    public string RutReceptor {
        get {
            return this.rutReceptorField;
        }
        set {
            this.rutReceptorField = value;
        }
    }
    
    /// <remarks/>
    public RespuestaDTEResultadoRecepcionEnvioEstadoRecepEnv EstadoRecepEnv {
        get {
            return this.estadoRecepEnvField;
        }
        set {
            this.estadoRecepEnvField = value;
        }
    }
    
    /// <remarks/>
    public string RecepEnvGlosa {
        get {
            return this.recepEnvGlosaField;
        }
        set {
            this.recepEnvGlosaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NroDTE {
        get {
            return this.nroDTEField;
        }
        set {
            this.nroDTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RecepcionDTE")]
    public RespuestaDTEResultadoRecepcionEnvioRecepcionDTE[] RecepcionDTE {
        get {
            return this.recepcionDTEField;
        }
        set {
            this.recepcionDTEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public enum RespuestaDTEResultadoRecepcionEnvioEstadoRecepEnv {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("90")]
    Item90,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("91")]
    Item91,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("99")]
    Item99,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public partial class RespuestaDTEResultadoRecepcionEnvioRecepcionDTE {
    
    private DTEType tipoDTEField;
    
    private string folioField;
    
    private System.DateTime fchEmisField;
    
    private string rUTEmisorField;
    
    private string rUTRecepField;
    
    private string mntTotalField;
    
    private RespuestaDTEResultadoRecepcionEnvioRecepcionDTEEstadoRecepDTE estadoRecepDTEField;
    
    private string recepDTEGlosaField;
    
    /// <remarks/>
    public DTEType TipoDTE {
        get {
            return this.tipoDTEField;
        }
        set {
            this.tipoDTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Folio {
        get {
            return this.folioField;
        }
        set {
            this.folioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FchEmis {
        get {
            return this.fchEmisField;
        }
        set {
            this.fchEmisField = value;
        }
    }
    
    /// <remarks/>
    public string RUTEmisor {
        get {
            return this.rUTEmisorField;
        }
        set {
            this.rUTEmisorField = value;
        }
    }
    
    /// <remarks/>
    public string RUTRecep {
        get {
            return this.rUTRecepField;
        }
        set {
            this.rUTRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string MntTotal {
        get {
            return this.mntTotalField;
        }
        set {
            this.mntTotalField = value;
        }
    }
    
    /// <remarks/>
    public RespuestaDTEResultadoRecepcionEnvioRecepcionDTEEstadoRecepDTE EstadoRecepDTE {
        get {
            return this.estadoRecepDTEField;
        }
        set {
            this.estadoRecepDTEField = value;
        }
    }
    
    /// <remarks/>
    public string RecepDTEGlosa {
        get {
            return this.recepDTEGlosaField;
        }
        set {
            this.recepDTEGlosaField = value;
        }
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sii.cl/SiiDte")]
//public enum DTEType {
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("33")]
//    Item33,
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("34")]
//    Item34,
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("46")]
//    Item46,
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("52")]
//    Item52,
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("56")]
//    Item56,
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlEnumAttribute("61")]
//    Item61,
//}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public enum RespuestaDTEResultadoRecepcionEnvioRecepcionDTEEstadoRecepDTE {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("99")]
    Item99,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public partial class RespuestaDTEResultadoResultadoDTE {
    
    private DTEType tipoDTEField;
    
    private string folioField;
    
    private System.DateTime fchEmisField;
    
    private string rUTEmisorField;
    
    private string rUTRecepField;
    
    private string mntTotalField;
    
    private string codEnvioField;
    
    private RespuestaDTEResultadoResultadoDTEEstadoDTE estadoDTEField;
    
    private string estadoDTEGlosaField;
    
    private string codRchDscField;
    
    /// <remarks/>
    public DTEType TipoDTE {
        get {
            return this.tipoDTEField;
        }
        set {
            this.tipoDTEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Folio {
        get {
            return this.folioField;
        }
        set {
            this.folioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime FchEmis {
        get {
            return this.fchEmisField;
        }
        set {
            this.fchEmisField = value;
        }
    }
    
    /// <remarks/>
    public string RUTEmisor {
        get {
            return this.rUTEmisorField;
        }
        set {
            this.rUTEmisorField = value;
        }
    }
    
    /// <remarks/>
    public string RUTRecep {
        get {
            return this.rUTRecepField;
        }
        set {
            this.rUTRecepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string MntTotal {
        get {
            return this.mntTotalField;
        }
        set {
            this.mntTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string CodEnvio {
        get {
            return this.codEnvioField;
        }
        set {
            this.codEnvioField = value;
        }
    }
    
    /// <remarks/>
    public RespuestaDTEResultadoResultadoDTEEstadoDTE EstadoDTE {
        get {
            return this.estadoDTEField;
        }
        set {
            this.estadoDTEField = value;
        }
    }
    
    /// <remarks/>
    public string EstadoDTEGlosa {
        get {
            return this.estadoDTEGlosaField;
        }
        set {
            this.estadoDTEGlosaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="negativeInteger")]
    public string CodRchDsc {
        get {
            return this.codRchDscField;
        }
        set {
            this.codRchDscField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sii.cl/SiiDte")]
public enum RespuestaDTEResultadoResultadoDTEEstadoDTE {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}
