// Generated by MyGeneration Version # (1.3.1.1)

using System;

namespace cfd.FacturaElectronica
{
	public class cfdLogLibroCV : _cfdLogLibroCV
	{
        public cfdLogLibroCV(string connstr)
        {
            this.ConnectionString = connstr;
        }
	}
}


