
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.1.1)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace Your.Namespace
{
	public abstract class _cfdLogLibroCV : SqlClientEntity
	{
		public _cfdLogLibroCV()
		{
			this.QuerySource = "cfdLogLibroCV";
			this.MappingName = "cfdLogLibroCV";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_cfdLogLibroCVLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Periodo)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Periodo, Periodo);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_cfdLogLibroCVLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Secuencia
			{
				get
				{
					return new SqlParameter("@Secuencia", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter FechaModificacion
			{
				get
				{
					return new SqlParameter("@FechaModificacion", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Secuencia = "secuencia";
            public const string FechaModificacion = "fechaModificacion";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Secuencia] = _cfdLogLibroCV.PropertyNames.Secuencia;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Secuencia = "Secuencia";
            public const string FechaModificacion = "FechaModificacion";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Secuencia] = _cfdLogLibroCV.ColumnNames.Secuencia;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Secuencia = "s_Secuencia";
            public const string FechaModificacion = "s_FechaModificacion";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Secuencia
	    {
			get
	        {
				return base.Getint(ColumnNames.Secuencia);
			}
			set
	        {
				base.Setint(ColumnNames.Secuencia, value);
			}
		}

		public virtual DateTime FechaModificacion
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.FechaModificacion);
			}
			set
	        {
				base.SetDateTime(ColumnNames.FechaModificacion, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Secuencia
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Secuencia) ? string.Empty : base.GetintAsString(ColumnNames.Secuencia);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Secuencia);
				else
					this.Secuencia = base.SetintAsString(ColumnNames.Secuencia, value);
			}
		}

		public virtual string s_FechaModificacion
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FechaModificacion) ? string.Empty : base.GetDateTimeAsString(ColumnNames.FechaModificacion);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FechaModificacion);
				else
					this.FechaModificacion = base.SetDateTimeAsString(ColumnNames.FechaModificacion, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Secuencia
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Secuencia, Parameters.Secuencia);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FechaModificacion
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FechaModificacion, Parameters.FechaModificacion);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Secuencia
		    {
				get
		        {
					if(_Secuencia_W == null)
	        	    {
						_Secuencia_W = TearOff.Secuencia;
					}
					return _Secuencia_W;
				}
			}

			public WhereParameter FechaModificacion
		    {
				get
		        {
					if(_FechaModificacion_W == null)
	        	    {
						_FechaModificacion_W = TearOff.FechaModificacion;
					}
					return _FechaModificacion_W;
				}
			}

			private WhereParameter _Secuencia_W = null;
			private WhereParameter _FechaModificacion_W = null;

			public void WhereClauseReset()
			{
				_Secuencia_W = null;
				_FechaModificacion_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Secuencia
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Secuencia, Parameters.Secuencia);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FechaModificacion
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FechaModificacion, Parameters.FechaModificacion);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Secuencia
		    {
				get
		        {
					if(_Secuencia_W == null)
	        	    {
						_Secuencia_W = TearOff.Secuencia;
					}
					return _Secuencia_W;
				}
			}

			public AggregateParameter FechaModificacion
		    {
				get
		        {
					if(_FechaModificacion_W == null)
	        	    {
						_FechaModificacion_W = TearOff.FechaModificacion;
					}
					return _FechaModificacion_W;
				}
			}

			private AggregateParameter _Secuencia_W = null;
			private AggregateParameter _FechaModificacion_W = null;

			public void AggregateClauseReset()
			{
				_Secuencia_W = null;
				_FechaModificacion_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_cfdLogLibroCVInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Secuencia.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_cfdLogLibroCVUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_cfdLogLibroCVDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Periodo);
			p.SourceColumn = ColumnNames.Periodo;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Secuencia);
			p.SourceColumn = ColumnNames.Secuencia;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FechaModificacion);
			p.SourceColumn = ColumnNames.FechaModificacion;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
