//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdFolios
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfd_FOL00100
    {
        public short SOPTYPE { get; set; }
        public string DOCID { get; set; }
        public int num_folio_desde { get; set; }
        public int num_folio_hasta { get; set; }
        public string ruta_codigo_autorizacion { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
