//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfdFolios
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCfdIdDocumentos
    {
        public short soptype { get; set; }
        public string docid { get; set; }
        public string SOPNUMBE { get; set; }
        public string commntid { get; set; }
        public string nombreTipoDoc { get; set; }
        public string carpetaFolio { get; set; }
    }
}
